name: Build program

on:
  push:
    branches-ignore:
      - docs
    tags:
      - v*
    paths:
      - src/**
      - include/**
      - makefile
      - .github/workflows/**

env:
  CEDEV_REPO: CE-Programming/toolchain
  CEDEV_PATH: ${{github.workspace}}/CEdev
  WORDLE_PATH: ${{github.workspace}}/ti-wordle
  RELEASE_NAME_PREFIX: TI Wordle

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Fetch CE-Programming toolchain version
        id: cedev-version
        run: |
          curl -sSL https://api.github.com/repos/${{ env.CEDEV_REPO }}/releases/latest | jq -r '"CEDEV_TAG=\(.tag_name)"' >> $GITHUB_ENV

      - name: Download CE-Programming toolchain
        id: cedev-download
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://github.com/${{ env.CEDEV_REPO }}/releases/download/${{ env.CEDEV_TAG }}/linux_CEdev_${{ env.CEDEV_TAG }}.tar.gz
          file-name: CEdev.tar.gz

      - name: Extract CE-Programming toolchain
        run: |
          tar -zxf ${{ steps.cedev-download.outputs.file-path }} CEdev

      - name: Add toolchain to executable path
        run: |
          echo "$CEDEV_PATH/bin" >> $GITHUB_PATH

      - name: Checkout repository (at tag)
        if: github.ref_type == 'tag'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
          path: ${{ env.WORDLE_PATH }}

      - name: Checkout repository
        if: github.ref_type != 'tag'
        uses: actions/checkout@v2
        with:
          path: ${{ env.WORDLE_PATH }}

      - name: Build program
        run: |
          make -C $WORDLE_PATH

      - name: Upload program binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: wordle-exe
          path: ${{ env.WORDLE_PATH }}/bin/*.8xp

      - name: Get tag body text
        id: tag-body
        if: github.ref_type == 'tag'
        run: |
          printf '%s' '::set-output name=tag-body::'
          git -C $WORDLE_PATH cat-file tag ${{ github.ref_name }} | sed ':a ; 1,5d; /^-----BEGIN PGP SIGNATURE-----$/,$d; s/%/%25/g; s/$/%0A/g' | tr -d '\n'

      - name: Create release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME_PREFIX }} ${{ github.ref_name }}
          body: ${{ steps.tag-body.outputs.tag-body }}
          files: ${{ env.WORDLE_PATH }}/bin/*.8xp
          generate_release_notes: false
